import { useEffect, useRef, useState } from "react";
import { ArrowRight, FileText, LoaderCircle, Sparkles } from "lucide-react";
import type { DemoSummary } from "./demo-model";
import "./report-planner.css";

export type PlanResult = {
  id: string;
  created_at: string;
  source: "live_openai";
  executed: false;
  model: string;
  elapsed_seconds: number;
  input_tokens: number | null;
  output_tokens: number | null;
  report_sha256: string;
  plan: {
    title: string;
    reported_failure: string;
    expected_behavior: string;
    hypothesis_to_test: string;
    steps: {
      title: string;
      kind: "setup" | "action" | "checkpoint";
      action: string;
      evidence_needed: string;
    }[];
    missing_details: string[];
    assumptions: string[];
    failure_evidence: string;
    success_evidence: string;
    related_recordings: { id: string; reason: string }[];
  };
};

export function ReportPlanner({
  report,
  onEdit,
  catalog,
  result,
  onResult,
  onChoose,
  onFresh,
}: {
  report: string;
  onEdit: (value: string) => void;
  catalog: DemoSummary[];
  result: PlanResult | null;
  onResult: (value: PlanResult | null) => void;
  onChoose: (id: string) => void;
  onFresh: () => void;
}) {
  const [busy, setBusy] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState("");
  const request = useRef<AbortController | null>(null);
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => () => request.current?.abort(), []);
  useEffect(() => {
    if (!busy) return;
    const started = Date.now();
    const timer = setInterval(
      () => setElapsed(Math.floor((Date.now() - started) / 1000)),
      1000,
    );
    return () => clearInterval(timer);
  }, [busy]);

  async function generate(e: React.FormEvent) {
    e.preventDefault();
    const controller = new AbortController();
    request.current?.abort();
    request.current = controller;
    setBusy(true);
    setElapsed(0);
    setError("");
    onResult(null);
    try {
      const response = await fetch("/api/report-plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ report: report.trim(), game: "mindustry" }),
        signal: controller.signal,
      });
      if (!response.ok) {
        const payload = await response.json().catch(() => null);
        throw new Error(
          typeof payload?.detail === "string"
            ? payload.detail
            : "The plan could not be generated. Try again or open a recorded case.",
        );
      }
      const value = (await response.json()) as PlanResult;
      if (!controller.signal.aborted) {
        onResult(value);
        setTimeout(() => {
          heading.current?.focus();
          heading.current?.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        }, 0);
      }
    } catch (err) {
      if (!controller.signal.aborted)
        setError(
          err instanceof Error
            ? err.message
            : "Planning failed. No game was executed.",
        );
    } finally {
      if (!controller.signal.aborted) setBusy(false);
    }
  }

  function edit(value: string) {
    request.current?.abort();
    setBusy(false);
    setError("");
    onEdit(value);
  }

  return (
    <section
      className="report-planner panel"
      aria-label="Live AI test planning"
    >
      <div className="planner-heading">
        <div>
          <div className="eyebrow">REPORT TO TEST PLAN</div>
          <h2 ref={heading} tabIndex={-1}>
            {result ? result.plan.title : "What would prove this bug?"}
          </h2>
        </div>
        <span className="planner-source">
          <Sparkles size={15} />{" "}
          {result ? "Generated by OpenAI" : "Live OpenAI request"}
        </span>
      </div>
      <p className="planner-intro">
        Describe the behavior in your own words. REPRO maps the actions and
        checkpoints needed to test it.
      </p>
      <details className="planner-report" open={!result}>
        <summary>
          {result
            ? `Player report: ${report.length > 140 ? report.slice(0, 140) + "…" : report}`
            : "Player report"}
          {result && <small>Click to edit</small>}
        </summary>
        <form
          onSubmit={generate}
          className={`planner-input ${result ? "compact" : ""}`}
        >
          <label>
            <span>Mindustry player report</span>
            <textarea
              value={report}
              onChange={(e) => edit(e.target.value)}
              required
              minLength={10}
              maxLength={8000}
              rows={result ? 2 : 4}
              placeholder="I removed a patch from my map, saved, and opened the map again. The entry was back."
            />
          </label>
          <div className="planner-submit">
            <button
              className="button primary"
              disabled={
                busy || report.trim().length < 10 || report.trim().length > 8000
              }
            >
              {busy ? (
                <LoaderCircle size={16} className="spin" />
              ) : (
                <Sparkles size={16} />
              )}
              {busy
                ? `Planning · ${elapsed}s`
                : result
                  ? "Generate a new plan"
                  : "Map the test with AI"}
            </button>
            <small>
              Your report is sent to OpenAI. This generates a plan; it does not
              run the game.
            </small>
          </div>
        </form>
      </details>
      {error && (
        <p className="error-banner" role="alert">
          {error}
        </p>
      )}
      {busy && (
        <div className="planner-wait" role="status">
          <LoaderCircle className="spin" size={20} />
          <div>
            <strong>Working out the trigger and the evidence</strong>
            <p>
              No game actions have been executed. Recorded cases remain
              available while this request runs.
            </p>
          </div>
        </div>
      )}
      {result ? (
        <>
          <div className="planner-provenance">
            <strong>PROPOSED PLAN · NOT EXECUTED</strong>
            <span>
              {result.model} · {result.elapsed_seconds.toFixed(1)}s ·{" "}
              {new Date(result.created_at).toLocaleTimeString()}
            </span>
          </div>
          <p className="planner-hypothesis">
            <span>Hypothesis to test</span>
            {result.plan.hypothesis_to_test}
          </p>
          <ol
            className={`planner-map${result.plan.steps.length === 4 ? " four-steps" : ""}`}
            aria-label="Proposed actions and evidence checkpoints"
          >
            {result.plan.steps.map((step, i) => (
              <li
                key={`${i}-${step.title}`}
                className={`planner-step ${step.kind}`}
              >
                <div className="planner-step-top">
                  <span>{String(i + 1).padStart(2, "0")}</span>
                  <small>{step.kind}</small>
                </div>
                <h3>{step.title}</h3>
                <p>{step.action}</p>
                <div className="planner-proof">
                  <strong>Evidence needed</strong>
                  <p>{step.evidence_needed}</p>
                </div>
              </li>
            ))}
          </ol>
          <div className="planner-criteria">
            <div>
              <span>To establish the failure</span>
              <p>{result.plan.failure_evidence}</p>
            </div>
            <div>
              <span>To verify a future fix</span>
              <p>{result.plan.success_evidence}</p>
            </div>
          </div>
          {(result.plan.missing_details.length > 0 ||
            result.plan.assumptions.length > 0) && (
            <details className="planner-questions">
              <summary>
                Details to confirm before execution (
                {result.plan.missing_details.length +
                  result.plan.assumptions.length}
                )
              </summary>
              <ul>
                {result.plan.missing_details.map((s, i) => (
                  <li key={`m${i}`}>{s}</li>
                ))}
                {result.plan.assumptions.map((s, i) => (
                  <li key={`a${i}`}>
                    <strong>Assumption:</strong> {s}
                  </li>
                ))}
              </ul>
            </details>
          )}
          <div className="planner-recordings">
            <div>
              <div className="eyebrow">PRIOR GAME EXECUTIONS</div>
              <h3>Compare with recorded evidence</h3>
              <p>
                These are separate investigations. A related report does not
                confirm your new report.
              </p>
            </div>
            {result.plan.related_recordings.map((item) => {
              const record = catalog.find((c) => c.id === item.id);
              return record ? (
                <button
                  key={item.id}
                  className="planner-recording"
                  onClick={() => onChoose(item.id)}
                >
                  <FileText size={20} />
                  <span>
                    <strong>{record.title}</strong>
                    <small>{item.reason}</small>
                  </span>
                  <ArrowRight size={18} />
                </button>
              ) : null;
            })}
            {!result.plan.related_recordings.length && (
              <p>
                No related recording was suggested. A fresh game investigation
                is needed.
              </p>
            )}
            <button className="button secondary small" onClick={onFresh}>
              Create a fresh investigation <ArrowRight size={14} />
            </button>
          </div>
          <details className="planner-details">
            <summary>Request details</summary>
            <p>
              {result.id}
              <br />
              {result.input_tokens ?? "Unknown"} input tokens ·{" "}
              {result.output_tokens ?? "Unknown"} output tokens
              <br />
              Report, game selection and a small catalog of report descriptions
              were supplied. No screenshots, source code, saved verdicts or
              patches were provided to this planner.
            </p>
          </details>
        </>
      ) : (
        !busy && (
          <div className="planner-start">
            <div className="planner-outline">
              <span>Starting state</span>
              <ArrowRight />
              <span>Trigger</span>
              <ArrowRight />
              <span>Observable result</span>
            </div>
            <p>
              The AI will propose a testable path and identify the evidence
              needed at each checkpoint.
            </p>
            <div className="planner-examples">
              {catalog.map((c) => (
                <button key={c.id} onClick={() => edit(c.sampleReport)}>
                  {c.title}
                  <ArrowRight size={14} />
                </button>
              ))}
            </div>
          </div>
        )
      )}
    </section>
  );
}
