"""Supplemental evaluator checks, authored after the REPRO model proposed its patch.
No model calls, no edits to the live case, and no changes to its recorded gates.
"""
import asyncio,hashlib,json,time
from pathlib import Path
from repro.computer.sandbox import DockerSandbox
from repro.config import Settings
from repro.models import Case
from repro.process import run
from repro.storage.store import Store
from repro.validation import parse_gradle_failures,test_command

TEST = r'''import arc.util.io.*;
import mindustry.content.*;
import mindustry.game.*;
import mindustry.world.blocks.defense.TargetDummy;
import mindustry.world.blocks.defense.TargetDummy.TargetDummyBuild;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;
import java.io.*;
import static org.junit.jupiter.api.Assertions.*;

public class ReproTargetDummySerializationTest{
    @BeforeAll
    public static void setup(){ ApplicationTests.launchApplication(); }

    private TargetDummyBuild fresh(Team buildingTeam){
        TargetDummyBuild build = ((TargetDummy)Blocks.targetDummy).new TargetDummyBuild();
        build.team = buildingTeam;
        build.boosting = true;
        build.unitArmor = 17f;
        build.resetTime = 90f;
        build.dummySize = 16f;
        return build;
    }

    private void roundTrip(TargetDummyBuild source, Team expectedTeam) throws IOException{
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        source.write(new Writes(new DataOutputStream(bytes)));
        assertEquals(21, bytes.size(), "Existing serialization layout must be retained");
        TargetDummyBuild loaded = fresh(source.team);
        loaded.read(new Reads(new DataInputStream(new ByteArrayInputStream(bytes.toByteArray()))), (byte)0);
        assertEquals(expectedTeam, loaded.unitTeam);
        assertEquals(-1, loaded.readUnitId);
        assertTrue(loaded.boosting);
        assertEquals(17f, loaded.unitArmor);
        assertEquals(90f, loaded.resetTime);
        assertEquals(16f, loaded.dummySize);
    }

    @ParameterizedTest
    @ValueSource(ints = {0, 1, 2})
    public void defaultTeamSavesBeforeFirstUpdate(int id) throws IOException{
        Team team = Team.get(id);
        TargetDummyBuild source = fresh(team);
        assertNull(source.unitTeam, "This regression must exercise the uninitialized value");
        roundTrip(source, team);
    }

    @Test
    public void explicitTeamIsPreserved() throws IOException{
        TargetDummyBuild source = fresh(Team.sharded);
        source.unitTeam = Team.crux;
        roundTrip(source, Team.crux);
    }
}
'''

async def main():
 output=Path('.repro/overnight-2026-09-15/target-dummy-controls');assert not output.exists();output.mkdir()
 source=Store(Settings().root); original=source.get('md-12579-terra-overnight-01')
 patch_path,_=source.artifact_path(original.id,original.patch_artifact);patch=patch_path.read_bytes()
 cfg=Settings(data_dir=output/'store',sandbox_dir=Path('/tmp/repro-overnight-controls'),worker_image='repro-worker:overnight-inputs-20260915')
 store=Store(cfg.root);case=Case(id='md12579-matched-control',report=original.report);worker=DockerSandbox(cfg,store,case)
 live=Path('/tmp/repro-oai-gaming-workspaces')/original.id
 assert not worker.repo.exists()
 await run(['cp','-cR',str(live/'repo'),str(worker.repo)],timeout=180)
 (worker.root/'gradle').rmdir()
 await run(['cp','-cR',str(live/'gradle'),str(worker.root/'gradle')],timeout=180)
 await run(['git','-C',str(worker.repo),'restore','--source='+original.report.target_commit,'--staged','--worktree','--','.'])
 await worker.baseline_source_is_clean()
 results={'scope':'Independent evaluator tests after the REPRO AI proposal; no changes to the live case, patch, or approval gates.','source_case':original.id,'target_commit':original.report.target_commit,'patch_sha256':hashlib.sha256(patch).hexdigest(),'regression_author':'Codex evaluator after patch generation; not generated by the REPRO investigator','runs':[]}
 def save(): (output/'result.json').write_text(json.dumps(results,indent=2)+'\n')
 async def execute(label,command):
  start=time.monotonic();code,log=await worker.exec(command,timeout=900,check=False,output_path=output/(label+'.log'))
  row={'label':label,'command':command,'network':'bridge','exit_code':code,'elapsed_seconds':round(time.monotonic()-start,3),'log_file':label+'.log','log_sha256':hashlib.sha256(log.encode()).hexdigest()}
  try:row['failing_tests']=parse_gradle_failures(log,code)
  except ValueError as exc:row['parse_error']=str(exc)
  results['runs'].append(row);save();print(label,code,row.get('failing_tests',row.get('parse_error')),flush=True)
 try:
  async with asyncio.timeout(1500):
   await worker.start(network=True,fresh_profile=True);results['worker_image']=await worker.image_id();results['worker_platform']=cfg.worker_platform
   await worker.baseline_source_is_clean();results['untouched_source_verified']=True;save()
   command=test_command(worker.adapter,network=True)
   await execute('untouched-online-baseline',command)
   await worker.baseline_source_is_clean()
   test_path=worker.repo/'tests/src/test/java/ReproTargetDummySerializationTest.java';assert not test_path.exists();test_path.write_text(TEST)
   (output/test_path.name).write_text(TEST);results['test_sha256']=hashlib.sha256(TEST.encode()).hexdigest()
   regression=command+['--tests','ReproTargetDummySerializationTest']
   await execute('serialization-baseline',regression)
   (output/'candidate.patch').write_bytes(patch)
   await run(['git','-C',str(worker.repo),'apply','--check',str((output/'candidate.patch').resolve())])
   await run(['git','-C',str(worker.repo),'apply',str((output/'candidate.patch').resolve())])
   await execute('serialization-candidate',regression)
 finally:
  await worker.stop();save()
 print('Saved',output,flush=True)
asyncio.run(main())
